import fetch from "node-fetch";
import getRandomInterviewCover from "../utils/getRandomInterviewCover.js";
import dotenv from "dotenv";

dotenv.config();
const GEMINI_API_KEY = process.env.GEMINI_KEY;

/**
 * Generate Interview Questions (console only, no DB)
 */
export const generateInterview = async (req, res) => {
  try {
    const { type, role, level, techstack, amount, userId } = req.body;
    
    console.log('🚀 GENERATING INTERVIEW');
    console.log('Parameters:', { type, role, level, techstack, amount, userId });

    if (!userId || isNaN(userId)) {
      return res.status(400).json({ error: 'Invalid userId - must be a number' });
    }
    if (!role || !type || !level || !techstack || !amount) {
      return res.status(400).json({ error: 'Missing required fields' });
    }

    const prompt = `
Prepare ${amount} interview questions for a job.
The job role is ${role}
The job experience level is ${level}.
The tech stack used in the job is: ${techstack}.
The focus between behavioural and technical questions should lean towards: ${type}.
Return ONLY a JSON array like ["Question 1", "Question 2", ...].
Do not ask candidates to write actual code.
The questions are going to be read by a voice assistant so do not use "/" or "*" or any special characters.
`;

    let questions;
    try {
      console.log('🤖 Calling Gemini...');
      const response = await fetch(
        `https://generativelanguage.googleapis.com/v1/models/gemini-2.5-flash:generateContent?key=${GEMINI_API_KEY}`,
        {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ contents: [{ parts: [{ text: prompt }] }] })
        }
      );

      const data = await response.json();
      const text = data?.candidates?.[0]?.content?.parts?.[0]?.text;

      if (!text) throw new Error("No text from AI");

      const cleanedText = text.trim().replace(/```json|```/g, '').trim();
      questions = JSON.parse(cleanedText);

      if (!Array.isArray(questions)) throw new Error('Not an array');

      console.log('✅ Generated Questions:', questions);
    } catch (err) {
      console.error("❌ Gemini failed:", err.message);
      return res.status(500).json({ error: `AI generation failed: ${err.message}` });
    }

    // ❌ NO DATABASE SAVE — just console output
    console.log('💾 Interview Info (Console Only):', {
      role,
      type,
      level,
      techstack: techstack.split(",").map(s => s.trim()),
      questions,
      amount: Number(amount),
      userId: Number(userId),
      finalized: true,
      coverImage: getRandomInterviewCover(),
      status: 'pending',
      createdAt: new Date().toISOString()
    });

    return res.status(200).json({ 
      message: 'Interview generated successfully (console only)',
      questions 
    });

  } catch (error) {
    console.error("❌ UNEXPECTED ERROR:", error);
    return res.status(500).json({ error: error.message });
  }
};

/**
 * Process Transcript (console only)
 */
export const processTranscript = async (transcript) => {
  console.log("\n════════ TRANSCRIPT RECEIVED ════════");
  transcript.forEach((msg, index) => {
    const speaker = msg.role === "user" ? "👤 USER" : "🤖 ASSISTANT";
    console.log(`[${index + 1}] ${speaker}: ${msg.text}`);
  });

  const transcriptText = transcript.map(t => `${t.role}: ${t.text}`).join("\n");

  console.log("\n📡 Sending transcript to Gemini for evaluation...");

  const feedbackRaw = await analyzeTranscript(transcriptText);

  console.log("\n🎉 FEEDBACK GENERATED BY GEMINI:");
  console.log(feedbackRaw);

  return feedbackRaw;
};

/**
 * Analyze Transcript with Gemini
 */
export const analyzeTranscript = async (transcript) => {
  const evaluationPrompt = `
You are a professional interviewer analyzing a mock interview.
I'll give you the transcript and you assess the candidate.
Please score the candidate from 0 to 100 in the following areas. 
Do NOT change category names. Do NOT add new categories.

Format your response EXACTLY like this:

**Communication Skills: [SCORE]/100**
[Detailed feedback]

**Technical Knowledge: [SCORE]/100**
[Detailed feedback]

**Problem-solving: [SCORE]/100**
[Detailed feedback]

**Cultural & Role Fit: [SCORE]/100**
[Detailed feedback]

**Confidence and Clarity: [SCORE]/100**
[Detailed feedback]

**Overall Feedback:**
[Summary]

Transcript:
${transcript}
`;

  try {
    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1/models/gemini-2.0-flash:generateContent?key=${GEMINI_API_KEY}`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ contents: [{ parts: [{ text: evaluationPrompt }] }] })
      }
    );

    const data = await response.json();
    const output = data?.candidates?.[0]?.content?.parts?.[0]?.text;
    if (!output) throw new Error("No feedback returned from Gemini");

    return output.trim();
  } catch (err) {
    console.error("❌ FEEDBACK MODEL FAILED:", err);
    return `Feedback generation failed: ${err.message}`;
  }
};
